// Language type definition
export type LanguageCode = 
  | "en" | "es" | "fr" | "de" | "it" | "pt" | "ru" | "ja" | "zh" | "ko" 
  | "nl" | "pl" | "tr" | "ar" | "th" | "vi";

export interface LanguageInfo {
  code: LanguageCode;
  name: string;
  nativeName: string;
  flag: string;
  rtl?: boolean; // Right-to-left languages
}

export const LANGUAGES: Record<LanguageCode, LanguageInfo> = {
  en: { code: "en", name: "English", nativeName: "English", flag: "🇬🇧" },
  es: { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  fr: { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  de: { code: "de", name: "German", nativeName: "Deutsch", flag: "🇩🇪" },
  it: { code: "it", name: "Italian", nativeName: "Italiano", flag: "🇮🇹" },
  pt: { code: "pt", name: "Portuguese", nativeName: "Português", flag: "🇵🇹" },
  ru: { code: "ru", name: "Russian", nativeName: "Русский", flag: "🇷🇺" },
  ja: { code: "ja", name: "Japanese", nativeName: "日本語", flag: "🇯🇵" },
  zh: { code: "zh", name: "Chinese", nativeName: "中文", flag: "🇨🇳" },
  ko: { code: "ko", name: "Korean", nativeName: "한국어", flag: "🇰🇷" },
  nl: { code: "nl", name: "Dutch", nativeName: "Nederlands", flag: "🇳🇱" },
  pl: { code: "pl", name: "Polish", nativeName: "Polski", flag: "🇵🇱" },
  tr: { code: "tr", name: "Turkish", nativeName: "Türkçe", flag: "🇹🇷" },
  ar: { code: "ar", name: "Arabic", nativeName: "العربية", flag: "🇸🇦", rtl: true },
  th: { code: "th", name: "Thai", nativeName: "ไทย", flag: "🇹🇭" },
  vi: { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt", flag: "🇻🇳" },
};

// Default translations
export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.skills": "Skills",
    "nav.leaderboard": "Leaderboard",
    "nav.arena": "Arena",
    "nav.community": "Community",
    "nav.dashboard": "Dashboard",
    "nav.studio": "Studio",
    "nav.creator": "Creator Hub",

    // Settings
    "settings.title": "Settings",
    "settings.user": "User",
    "settings.themes": "Themes",
    "settings.language": "Language",
    "settings.notifications": "Notifications",
    "settings.dark_mode": "Dark Mode",
    "settings.light_mode": "Light Mode",
    "settings.profile": "Profile & Avatar",
    "settings.logout": "Logout",
    "settings.login": "Login",

    // Common
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.create": "Create",
  },
  es: {
    "nav.home": "Inicio",
    "nav.skills": "Habilidades",
    "nav.leaderboard": "Tabla de Clasificación",
    "nav.arena": "Arena",
    "nav.community": "Comunidad",
    "nav.dashboard": "Panel",
    "nav.studio": "Estudio",
    "nav.creator": "Centro de Creadores",
    "settings.title": "Configuración",
    "settings.user": "Usuario",
    "settings.themes": "Temas",
    "settings.language": "Idioma",
    "settings.notifications": "Notificaciones",
    "settings.dark_mode": "Modo Oscuro",
    "settings.light_mode": "Modo Claro",
    "settings.profile": "Perfil y Avatar",
    "settings.logout": "Cerrar Sesión",
    "settings.login": "Iniciar Sesión",
    "common.loading": "Cargando...",
    "common.error": "Error",
    "common.success": "Éxito",
    "common.cancel": "Cancelar",
    "common.save": "Guardar",
    "common.delete": "Eliminar",
    "common.edit": "Editar",
    "common.create": "Crear",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.skills": "Compétences",
    "nav.leaderboard": "Classement",
    "nav.arena": "Arène",
    "nav.community": "Communauté",
    "nav.dashboard": "Tableau de Bord",
    "nav.studio": "Studio",
    "nav.creator": "Hub Créateur",
    "settings.title": "Paramètres",
    "settings.user": "Utilisateur",
    "settings.themes": "Thèmes",
    "settings.language": "Langue",
    "settings.notifications": "Notifications",
    "settings.dark_mode": "Mode Sombre",
    "settings.light_mode": "Mode Clair",
    "settings.profile": "Profil et Avatar",
    "settings.logout": "Déconnexion",
    "settings.login": "Connexion",
    "common.loading": "Chargement...",
    "common.error": "Erreur",
    "common.success": "Succès",
    "common.cancel": "Annuler",
    "common.save": "Enregistrer",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.create": "Créer",
  },
  de: {
    "nav.home": "Startseite",
    "nav.skills": "Fähigkeiten",
    "nav.leaderboard": "Rangliste",
    "nav.arena": "Arena",
    "nav.community": "Gemeinschaft",
    "nav.dashboard": "Dashboard",
    "nav.studio": "Studio",
    "nav.creator": "Creator Hub",
    "settings.title": "Einstellungen",
    "settings.user": "Benutzer",
    "settings.themes": "Themen",
    "settings.language": "Sprache",
    "settings.notifications": "Benachrichtigungen",
    "settings.dark_mode": "Dunkler Modus",
    "settings.light_mode": "Heller Modus",
    "settings.profile": "Profil und Avatar",
    "settings.logout": "Abmelden",
    "settings.login": "Anmelden",
    "common.loading": "Lädt...",
    "common.error": "Fehler",
    "common.success": "Erfolg",
    "common.cancel": "Abbrechen",
    "common.save": "Speichern",
    "common.delete": "Löschen",
    "common.edit": "Bearbeiten",
    "common.create": "Erstellen",
  },
  it: {
    "nav.home": "Home",
    "nav.skills": "Competenze",
    "nav.leaderboard": "Classifiche",
    "nav.arena": "Arena",
    "nav.community": "Comunità",
    "nav.dashboard": "Pannello",
    "nav.studio": "Studio",
    "nav.creator": "Hub Creatori",
    "settings.title": "Impostazioni",
    "settings.user": "Utente",
    "settings.themes": "Temi",
    "settings.language": "Lingua",
    "settings.notifications": "Notifiche",
    "settings.dark_mode": "Modalità Scura",
    "settings.light_mode": "Modalità Chiara",
    "settings.profile": "Profilo e Avatar",
    "settings.logout": "Esci",
    "settings.login": "Accedi",
    "common.loading": "Caricamento...",
    "common.error": "Errore",
    "common.success": "Successo",
    "common.cancel": "Annulla",
    "common.save": "Salva",
    "common.delete": "Elimina",
    "common.edit": "Modifica",
    "common.create": "Crea",
  },
  pt: {
    "nav.home": "Início",
    "nav.skills": "Habilidades",
    "nav.leaderboard": "Classificação",
    "nav.arena": "Arena",
    "nav.community": "Comunidade",
    "nav.dashboard": "Painel",
    "nav.studio": "Estúdio",
    "nav.creator": "Hub de Criadores",
    "settings.title": "Configurações",
    "settings.user": "Usuário",
    "settings.themes": "Temas",
    "settings.language": "Idioma",
    "settings.notifications": "Notificações",
    "settings.dark_mode": "Modo Escuro",
    "settings.light_mode": "Modo Claro",
    "settings.profile": "Perfil e Avatar",
    "settings.logout": "Sair",
    "settings.login": "Entrar",
    "common.loading": "Carregando...",
    "common.error": "Erro",
    "common.success": "Sucesso",
    "common.cancel": "Cancelar",
    "common.save": "Salvar",
    "common.delete": "Deletar",
    "common.edit": "Editar",
    "common.create": "Criar",
  },
  ru: {
    "nav.home": "Главная",
    "nav.skills": "Навыки",
    "nav.leaderboard": "Таблица Лидеров",
    "nav.arena": "Арена",
    "nav.community": "Сообщество",
    "nav.dashboard": "Панель",
    "nav.studio": "Студия",
    "nav.creator": "Центр Создателя",
    "settings.title": "Настройки",
    "settings.user": "Пользователь",
    "settings.themes": "Темы",
    "settings.language": "Язык",
    "settings.notifications": "Уведомления",
    "settings.dark_mode": "Темный Режим",
    "settings.light_mode": "Светлый Режим",
    "settings.profile": "Профиль и Аватар",
    "settings.logout": "Выход",
    "settings.login": "Вход",
    "common.loading": "Загрузка...",
    "common.error": "Ошибка",
    "common.success": "Успех",
    "common.cancel": "Отмена",
    "common.save": "Сохранить",
    "common.delete": "Удалить",
    "common.edit": "Редактировать",
    "common.create": "Создать",
  },
  ja: {
    "nav.home": "ホーム",
    "nav.skills": "スキル",
    "nav.leaderboard": "リーダーボード",
    "nav.arena": "アリーナ",
    "nav.community": "コミュニティ",
    "nav.dashboard": "ダッシュボード",
    "nav.studio": "スタジオ",
    "nav.creator": "クリエイターハブ",
    "settings.title": "設定",
    "settings.user": "ユーザー",
    "settings.themes": "テーマ",
    "settings.language": "言語",
    "settings.notifications": "通知",
    "settings.dark_mode": "ダークモード",
    "settings.light_mode": "ライトモード",
    "settings.profile": "プロフィール＆アバター",
    "settings.logout": "ログアウト",
    "settings.login": "ログイン",
    "common.loading": "読み込み中...",
    "common.error": "エラー",
    "common.success": "成功",
    "common.cancel": "キャンセル",
    "common.save": "保存",
    "common.delete": "削除",
    "common.edit": "編集",
    "common.create": "作成",
  },
  zh: {
    "nav.home": "主页",
    "nav.skills": "技能",
    "nav.leaderboard": "排行榜",
    "nav.arena": "竞技场",
    "nav.community": "社区",
    "nav.dashboard": "仪表板",
    "nav.studio": "工作室",
    "nav.creator": "创作者中心",
    "settings.title": "设置",
    "settings.user": "用户",
    "settings.themes": "主题",
    "settings.language": "语言",
    "settings.notifications": "通知",
    "settings.dark_mode": "深色模式",
    "settings.light_mode": "浅色模式",
    "settings.profile": "个人资料和头像",
    "settings.logout": "登出",
    "settings.login": "登录",
    "common.loading": "加载中...",
    "common.error": "错误",
    "common.success": "成功",
    "common.cancel": "取消",
    "common.save": "保存",
    "common.delete": "删除",
    "common.edit": "编辑",
    "common.create": "创建",
  },
  ko: {
    "nav.home": "홈",
    "nav.skills": "스킬",
    "nav.leaderboard": "순위표",
    "nav.arena": "경기장",
    "nav.community": "커뮤니티",
    "nav.dashboard": "대시보드",
    "nav.studio": "스튜디오",
    "nav.creator": "크리에이터 허브",
    "settings.title": "설정",
    "settings.user": "사용자",
    "settings.themes": "테마",
    "settings.language": "언어",
    "settings.notifications": "알림",
    "settings.dark_mode": "다크 모드",
    "settings.light_mode": "라이트 모드",
    "settings.profile": "프로필 및 아바타",
    "settings.logout": "로그아웃",
    "settings.login": "로그인",
    "common.loading": "로딩 중...",
    "common.error": "오류",
    "common.success": "성공",
    "common.cancel": "취소",
    "common.save": "저장",
    "common.delete": "삭제",
    "common.edit": "편집",
    "common.create": "생성",
  },
  nl: {
    "nav.home": "Startpagina",
    "nav.skills": "Vaardigheden",
    "nav.leaderboard": "Ranglijst",
    "nav.arena": "Arena",
    "nav.community": "Gemeenschap",
    "nav.dashboard": "Dashboard",
    "nav.studio": "Studio",
    "nav.creator": "Creator Hub",
    "settings.title": "Instellingen",
    "settings.user": "Gebruiker",
    "settings.themes": "Thema's",
    "settings.language": "Taal",
    "settings.notifications": "Meldingen",
    "settings.dark_mode": "Donkere Modus",
    "settings.light_mode": "Lichte Modus",
    "settings.profile": "Profiel & Avatar",
    "settings.logout": "Afmelden",
    "settings.login": "Aanmelden",
    "common.loading": "Laden...",
    "common.error": "Fout",
    "common.success": "Succes",
    "common.cancel": "Annuleren",
    "common.save": "Opslaan",
    "common.delete": "Verwijderen",
    "common.edit": "Bewerken",
    "common.create": "Maken",
  },
  pl: {
    "nav.home": "Strona Główna",
    "nav.skills": "Umiejętności",
    "nav.leaderboard": "Ranking",
    "nav.arena": "Arena",
    "nav.community": "Społeczność",
    "nav.dashboard": "Panel",
    "nav.studio": "Studio",
    "nav.creator": "Hub Twórców",
    "settings.title": "Ustawienia",
    "settings.user": "Użytkownik",
    "settings.themes": "Motywy",
    "settings.language": "Język",
    "settings.notifications": "Powiadomienia",
    "settings.dark_mode": "Tryb Ciemny",
    "settings.light_mode": "Tryb Jasny",
    "settings.profile": "Profil i Avatar",
    "settings.logout": "Wyloguj",
    "settings.login": "Zaloguj",
    "common.loading": "Ładowanie...",
    "common.error": "Błąd",
    "common.success": "Powodzenie",
    "common.cancel": "Anuluj",
    "common.save": "Zapisz",
    "common.delete": "Usuń",
    "common.edit": "Edytuj",
    "common.create": "Utwórz",
  },
  tr: {
    "nav.home": "Ana Sayfa",
    "nav.skills": "Beceriler",
    "nav.leaderboard": "Skor Tablosu",
    "nav.arena": "Arena",
    "nav.community": "Topluluk",
    "nav.dashboard": "Gösterge Paneli",
    "nav.studio": "Stüdyo",
    "nav.creator": "Yaratıcı Merkezi",
    "settings.title": "Ayarlar",
    "settings.user": "Kullanıcı",
    "settings.themes": "Temalar",
    "settings.language": "Dil",
    "settings.notifications": "Bildirimler",
    "settings.dark_mode": "Koyu Mod",
    "settings.light_mode": "Açık Mod",
    "settings.profile": "Profil ve Avatar",
    "settings.logout": "Çıkış Yap",
    "settings.login": "Giriş Yap",
    "common.loading": "Yükleniyor...",
    "common.error": "Hata",
    "common.success": "Başarılı",
    "common.cancel": "İptal",
    "common.save": "Kaydet",
    "common.delete": "Sil",
    "common.edit": "Düzenle",
    "common.create": "Oluştur",
  },
  ar: {
    "nav.home": "الصفحة الرئيسية",
    "nav.skills": "المهارات",
    "nav.leaderboard": "جدول الترتيب",
    "nav.arena": "الساحة",
    "nav.community": "المجتمع",
    "nav.dashboard": "لوحة التحكم",
    "nav.studio": "الاستوديو",
    "nav.creator": "مركز الإبداع",
    "settings.title": "الإعدادات",
    "settings.user": "المستخدم",
    "settings.themes": "المظاهر",
    "settings.language": "اللغة",
    "settings.notifications": "الإخطارات",
    "settings.dark_mode": "الوضع الداكن",
    "settings.light_mode": "الوضع الفاتح",
    "settings.profile": "الملف الشخصي والصورة الرمزية",
    "settings.logout": "تسجيل الخروج",
    "settings.login": "تسجيل الدخول",
    "common.loading": "جاري التحميل...",
    "common.error": "خطأ",
    "common.success": "نجاح",
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.create": "إنشاء",
  },
  th: {
    "nav.home": "หน้าแรก",
    "nav.skills": "ทักษะ",
    "nav.leaderboard": "ตารางอันดับ",
    "nav.arena": "อリนา",
    "nav.community": "ชุมชน",
    "nav.dashboard": "แดชบอร์ด",
    "nav.studio": "สตูดิโอ",
    "nav.creator": "ศูนย์ผู้สร้าง",
    "settings.title": "การตั้งค่า",
    "settings.user": "ผู้ใช้",
    "settings.themes": "ธีม",
    "settings.language": "ภาษา",
    "settings.notifications": "การแจ้งเตือน",
    "settings.dark_mode": "โหมดมืด",
    "settings.light_mode": "โหมดสว่าง",
    "settings.profile": "โปรไฟล์และอวตาร์",
    "settings.logout": "ออกจากระบบ",
    "settings.login": "เข้าสู่ระบบ",
    "common.loading": "กำลังโหลด...",
    "common.error": "ข้อผิดพลาด",
    "common.success": "สำเร็จ",
    "common.cancel": "ยกเลิก",
    "common.save": "บันทึก",
    "common.delete": "ลบ",
    "common.edit": "แก้ไข",
    "common.create": "สร้าง",
  },
  vi: {
    "nav.home": "Trang Chủ",
    "nav.skills": "Kĩ Năng",
    "nav.leaderboard": "Bảng Xếp Hạng",
    "nav.arena": "Đấu Trường",
    "nav.community": "Cộng Đồng",
    "nav.dashboard": "Bảng Điều Khiển",
    "nav.studio": "Xưởng Làm Phim",
    "nav.creator": "Trung Tâm Nhà Sáng Tạo",
    "settings.title": "Cài Đặt",
    "settings.user": "Người Dùng",
    "settings.themes": "Chủ Đề",
    "settings.language": "Ngôn Ngữ",
    "settings.notifications": "Thông Báo",
    "settings.dark_mode": "Chế Độ Tối",
    "settings.light_mode": "Chế Độ Sáng",
    "settings.profile": "Hồ Sơ và Hình Đại Diện",
    "settings.logout": "Đăng Xuất",
    "settings.login": "Đăng Nhập",
    "common.loading": "Đang Tải...",
    "common.error": "Lỗi",
    "common.success": "Thành Công",
    "common.cancel": "Hủy",
    "common.save": "Lưu",
    "common.delete": "Xóa",
    "common.edit": "Chỉnh Sửa",
    "common.create": "Tạo",
  },
};

export function t(key: string, language: LanguageCode = "en"): string {
  return TRANSLATIONS[language]?.[key] ?? TRANSLATIONS.en[key] ?? key;
}
